[package]
name = "sentiric-sip-core"
version = "1.5.1" # Major feature bump
edition = "2021"
description = "High-performance SIP (RFC 3261) engine with transaction safety and RFC-compliant URI parsing."
authors = ["Sentiric Team"]
license = "AGPL-3.0"

[dependencies]
tokio = { version = "1", features = ["net", "sync", "rt", "time"] }
tracing = "0.1"
regex = "1"
once_cell = "1"